import Link from 'next/link';
import { AlertCircle, CheckCircle2, Circle, Clock3, Download, FileText } from 'lucide-react';
import { DeliverableStatus, MilestoneStatus, MilestoneStakeholderLane, MilestoneStakeholderState, Prisma, ReviewDecision, Role } from '@prisma/client';
import { reviewDeliverableAction } from '@/app/actions/documents';
import { reviewMilestoneAction, updateMilestoneStakeholderStatusAction } from '@/app/actions/workflows';
import { MilestoneUploadForm } from '@/components/documents/MilestoneUploadForm';
import { SubmitButton } from '@/components/ui/FormButtons';

type MilestoneItem = Prisma.MilestoneGetPayload<{ include: {
  template: { select: { phaseName: true } };
  stakeholderStatuses: { include: { updatedBy: { select: { name: true } } } };
  deliverables: { include: { uploader: { select: { name: true } }; reviewer: { select: { name: true } } } };
  reviews: { include: { reviewer: { select: { name: true } } } };
} }>;
type Props = { startupId: string; milestones: MilestoneItem[]; role: Role; canAssign: boolean; canReview: boolean; canUpload: boolean };
const inputClass = 'h-10 w-full rounded-input border bg-white px-3 text-sm outline-none focus:border-prise-primary';
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase();

export function MilestonePlan({ startupId, milestones, role, canAssign, canReview, canUpload }: Props) {
  const editableLane = role === Role.FOUNDER ? MilestoneStakeholderLane.STARTUP : role === Role.MENTOR ? MilestoneStakeholderLane.MENTOR : role === Role.PROGRAM_LEAD || role === Role.PROGRAM_TEAM ? MilestoneStakeholderLane.PROGRAM : null;
  const phases = [...milestones.reduce((groups, milestone) => {
    const key = `${milestone.phase}|${milestone.template?.phaseName ?? `Phase ${milestone.phase}`}`;
    const group = groups.get(key) ?? [];
    group.push(milestone);
    groups.set(key, group);
    return groups;
  }, new Map<string, MilestoneItem[]>()).entries()];

  return <section id="milestones" className="scroll-mt-20 rounded-card border bg-white p-5 shadow-card sm:p-6">
    <div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-base font-semibold">Personalized milestone plan</h2><p className="mt-1 text-sm text-prise-text-secondary">{milestones.length} selected outcomes · startup, mentor and program progress stays visible together.</p></div>{canAssign ? <Link href={`/startups/${startupId}/milestones/assign`} className="rounded-button bg-prise-primary px-3 py-2 text-sm font-semibold text-white">Edit plan</Link> : null}</div>
    {milestones.length ? <div className="space-y-4">{phases.map(([phaseKey, items]) => { const [phaseNumber, phaseName] = phaseKey.split('|'); return <details key={phaseKey} open className="overflow-hidden rounded-xl border border-prise-border"><summary className="cursor-pointer list-none bg-slate-50 px-4 py-3"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-bold uppercase tracking-[.12em] text-prise-primary">Phase {phaseNumber}</div><div className="mt-0.5 text-sm font-semibold">{phaseName}</div></div><span className="text-xs text-prise-text-secondary">{items.filter((item) => item.status === MilestoneStatus.APPROVED).length}/{items.length} approved</span></div></summary><div className="divide-y">{items.map((milestone) => <details key={milestone.id} className="p-4"><summary className="cursor-pointer list-none"><div className="flex flex-col gap-4"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{milestone.title}</div><p className="mt-1 text-xs leading-5 text-prise-text-secondary">{milestone.keyActivity || milestone.deliverable || 'Track the agreed outcome and supporting evidence.'}</p></div><Badge value={milestone.status} /></div><div className="grid grid-cols-3 gap-2">{Object.values(MilestoneStakeholderLane).map((lane) => <LaneStatus key={lane} lane={lane} state={resolvedLaneState(milestone.status, lane, milestone.stakeholderStatuses.find((item) => item.lane === lane)?.state)} />)}</div></div></summary><div className="mt-4 space-y-4 border-t pt-4">
        {editableLane ? <form action={updateMilestoneStakeholderStatusAction} className="grid gap-2 rounded-xl bg-prise-page p-3 sm:grid-cols-[150px_1fr_auto]"><input type="hidden" name="milestoneId" value={milestone.id} /><input type="hidden" name="lane" value={editableLane} /><select name="state" defaultValue={resolvedLaneState(milestone.status, editableLane, milestone.stakeholderStatuses.find((item) => item.lane === editableLane)?.state)} className={inputClass}>{laneStates(editableLane).map((value) => <option key={value}>{value.replaceAll('_', ' ')}</option>)}</select><input name="note" defaultValue={milestone.stakeholderStatuses.find((item) => item.lane === editableLane)?.note ?? ''} placeholder={`Optional ${label(editableLane)} update`} className={inputClass} /><SubmitButton className="!py-2">Update my status</SubmitButton></form> : null}
        {canUpload ? <MilestoneUploadForm milestoneId={milestone.id} /> : null}
        <EvidenceList milestone={milestone} canReview={canReview} />
        {milestone.reviews[0] ? <div className="rounded-input bg-prise-page p-3 text-xs text-prise-text-secondary">Latest review by {milestone.reviews[0].reviewer.name}: {label(milestone.reviews[0].decision)}{milestone.reviews[0].feedback ? ` · ${milestone.reviews[0].feedback}` : ''}</div> : null}
        {canReview ? <form action={reviewMilestoneAction} className="grid gap-2 sm:grid-cols-[180px_1fr_auto]"><input type="hidden" name="milestoneId" value={milestone.id} /><select name="decision" defaultValue={ReviewDecision.COMMENTED} className={inputClass}>{Object.values(ReviewDecision).map((value) => <option key={value}>{value}</option>)}</select><input name="feedback" placeholder="General milestone feedback" className={inputClass} /><SubmitButton className="!py-2">Record review</SubmitButton></form> : null}
      </div></details>)}</div></details>; })}</div> : <div className="rounded-input border border-dashed bg-prise-page p-5"><p className="text-sm font-semibold">No milestones assigned yet</p><p className="mt-1 text-xs leading-5 text-prise-text-secondary">Select only the outcomes that materially move this startup forward.</p></div>}
  </section>;
}

function EvidenceList({ milestone, canReview }: { milestone: MilestoneItem; canReview: boolean }) {
  return <div><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><FileText size={15} className="text-prise-primary" />Evidence files <span className="text-xs font-normal text-prise-text-secondary">({milestone.deliverables.length})</span></div>{milestone.deliverables.length ? <div className="space-y-2">{milestone.deliverables.map((file) => <div key={file.id} className="rounded-xl border bg-white p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><a href={`/api/documents/${file.id}`} className="inline-flex max-w-full items-center gap-2 text-sm font-semibold text-prise-primary"><Download size={14} /><span className="truncate">{file.name}</span></a><div className="mt-1 text-[11px] text-prise-text-secondary">v{file.version} · {file.uploader?.name ?? 'Team member'} · {file.sizeBytes ? `${(file.sizeBytes / 1024 / 1024).toFixed(1)} MB` : 'file'}</div></div><Badge value={file.status} /></div>{file.description ? <p className="mt-2 text-xs text-prise-text-secondary">{file.description}</p> : null}{file.feedback ? <p className="mt-2 rounded-lg bg-prise-page p-2 text-xs text-prise-text-secondary">Review: {file.feedback}</p> : null}{canReview && file.status === DeliverableStatus.SUBMITTED ? <form action={reviewDeliverableAction} className="mt-3 grid gap-2 sm:grid-cols-[150px_1fr_auto]"><input type="hidden" name="deliverableId" value={file.id} /><select name="status" defaultValue={DeliverableStatus.APPROVED} className={inputClass}><option value={DeliverableStatus.APPROVED}>APPROVE</option><option value={DeliverableStatus.NEEDS_REVISION}>NEEDS REVISION</option></select><input name="feedback" placeholder="Review feedback" className={inputClass} /><SubmitButton className="!py-2">Review</SubmitButton></form> : null}</div>)}</div> : <p className="rounded-xl border border-dashed p-4 text-xs text-prise-text-secondary">No evidence attached yet.</p>}</div>;
}
function Badge({ value }: { value: string }) { return <span className="shrink-0 rounded-pill bg-prise-page px-2.5 py-1 text-[11px] font-semibold text-prise-text-secondary">{label(value)}</span>; }
function LaneStatus({ lane, state }: { lane: MilestoneStakeholderLane; state: MilestoneStakeholderState }) { const Icon = state === MilestoneStakeholderState.APPROVED || state === MilestoneStakeholderState.SUBMITTED ? CheckCircle2 : state === MilestoneStakeholderState.IN_PROGRESS ? Clock3 : state === MilestoneStakeholderState.NEEDS_REVISION || state === MilestoneStakeholderState.BLOCKED ? AlertCircle : Circle; const tone = state === MilestoneStakeholderState.APPROVED || state === MilestoneStakeholderState.SUBMITTED ? 'bg-success-bg text-success' : state === MilestoneStakeholderState.IN_PROGRESS ? 'bg-warning-bg text-warning' : state === MilestoneStakeholderState.NEEDS_REVISION || state === MilestoneStakeholderState.BLOCKED ? 'bg-danger-bg text-danger' : 'bg-slate-100 text-slate-500'; return <div className={`rounded-lg px-2 py-2 text-center ${tone}`} title={`${label(lane)}: ${label(state)}`}><Icon size={15} className="mx-auto" /><div className="mt-1 text-[10px] font-bold uppercase tracking-wide">{label(lane)}</div><div className="mt-0.5 hidden text-[10px] sm:block">{label(state)}</div></div>; }
function laneStates(lane: MilestoneStakeholderLane) { return lane === MilestoneStakeholderLane.STARTUP ? [MilestoneStakeholderState.NOT_STARTED, MilestoneStakeholderState.IN_PROGRESS, MilestoneStakeholderState.SUBMITTED, MilestoneStakeholderState.BLOCKED] : [MilestoneStakeholderState.NOT_STARTED, MilestoneStakeholderState.IN_PROGRESS, MilestoneStakeholderState.APPROVED, MilestoneStakeholderState.NEEDS_REVISION]; }
function resolvedLaneState(overall: MilestoneStatus, lane: MilestoneStakeholderLane, actual?: MilestoneStakeholderState) { if (actual) return actual; if (overall === MilestoneStatus.APPROVED) return lane === MilestoneStakeholderLane.STARTUP ? MilestoneStakeholderState.SUBMITTED : MilestoneStakeholderState.APPROVED; if (lane === MilestoneStakeholderLane.STARTUP && overall === MilestoneStatus.SUBMITTED) return MilestoneStakeholderState.SUBMITTED; if (overall === MilestoneStatus.IN_PROGRESS) return MilestoneStakeholderState.IN_PROGRESS; if (overall === MilestoneStatus.NEEDS_REVISION && lane === MilestoneStakeholderLane.STARTUP) return MilestoneStakeholderState.BLOCKED; return MilestoneStakeholderState.NOT_STARTED; }
