import { Archive, Check, Circle, Download } from 'lucide-react';
import { OnboardingStatus, Prisma } from '@prisma/client';
import { archiveOnboardingDocumentAction } from '@/app/actions/documents';
import { reviewOnboardingAction } from '@/app/actions/workflows';
import { OnboardingUploadForm } from '@/components/documents/OnboardingUploadForm';
import { ConfirmButton, SubmitButton } from '@/components/ui/FormButtons';

type Item = Prisma.OnboardingItemGetPayload<{ include: { documents: { include: { uploader: { select: { name: true } } } } } }>;
const itemLabel: Record<string, string> = { AGREEMENT: 'Agreement', BASELINE: 'Baseline assessment', PITCH_VIDEO: '2-minute pitch video', LOGO: 'Logo', FEE_PAYMENT: 'Fee payment', DOCUMENT_FOLDER: 'Document folder' };
const inputClass = 'h-10 w-full rounded-input border bg-white px-3 text-sm outline-none focus:border-prise-primary';

export function OnboardingChecklist({ items, canReview, canUpload, currentUserId }: { items: Item[]; canReview: boolean; canUpload: boolean; currentUserId: string }) {
  return <div className="divide-y">{items.map((item) => { const complete = item.status === OnboardingStatus.SUBMITTED || item.status === OnboardingStatus.APPROVED; return <div key={item.id} className="py-4"><div className="grid gap-3 md:grid-cols-[minmax(180px,1fr)_minmax(300px,1.5fr)] md:items-center"><div className="flex items-center gap-3"><div className={`flex h-8 w-8 items-center justify-center rounded-full ${complete ? 'bg-success-bg text-success' : item.status === OnboardingStatus.NEEDS_REVISION ? 'bg-danger-bg text-danger' : 'bg-warning-bg text-warning'}`}>{complete ? <Check size={16} /> : <Circle size={15} />}</div><div><div className="text-sm font-semibold">{itemLabel[item.type]}</div><div className="text-xs text-prise-text-secondary">{item.status.replaceAll('_', ' ').toLowerCase()}</div></div></div>{canReview ? <form action={reviewOnboardingAction} className="grid gap-2 sm:grid-cols-[1fr_1.4fr_auto]"><input type="hidden" name="itemId" value={item.id} /><select name="status" defaultValue={item.status} className={inputClass}>{Object.values(OnboardingStatus).map((value) => <option key={value}>{value}</option>)}</select><input name="remarks" defaultValue={item.remarks ?? ''} placeholder="Decision note" className={inputClass} /><SubmitButton className="!py-2">Save</SubmitButton></form> : <p className="text-sm text-prise-text-secondary">{item.remarks || 'No review note'}</p>}</div>{item.documents.length ? <div className="ml-11 mt-3 flex flex-wrap gap-2">{item.documents.map((document) => <div key={document.id} className="inline-flex items-center rounded-lg border"><a href={`/api/onboarding-documents/${document.id}`} className="inline-flex items-center gap-2 px-3 py-2 text-xs font-semibold text-prise-primary"><Download size={13} />{document.name} · v{document.version}</a>{(canReview || (canUpload && document.uploaderId === currentUserId && item.status !== OnboardingStatus.APPROVED)) ? <form action={archiveOnboardingDocumentAction} className="border-l"><input type="hidden" name="onboardingDocumentId" value={document.id} /><ConfirmButton message="Archive this file version? It remains in audit history." className="!rounded-none !px-2" ><Archive size={13} /></ConfirmButton></form> : null}</div>)}</div> : null}{canUpload && item.status !== OnboardingStatus.APPROVED && item.status !== OnboardingStatus.NA ? <div className="ml-11"><OnboardingUploadForm onboardingItemId={item.id} /></div> : null}</div>; })}</div>;
}
