import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AlertTriangle, CheckCircle2, IndianRupee, MapPin, Pencil, Plus, ShieldCheck, Target } from 'lucide-react';
import { DeliverableStatus, MilestoneStatus, PaymentStatus, Priority, Role, StartupMemberRole, StartupStatus, SupportRequestStatus, TaskStatus } from '@prisma/client';
import {
  createPaymentAction, createStartupMemberAction, createSupportAction, createTaskAction, deletePaymentAction, deleteSupportAction,
  deleteTaskAction, updatePaymentAction, updateSupportAction, updateTaskAction,
  reviewStartupApplicationAction, updateStartupMemberAction,
} from '@/app/actions/workflows';
import { MilestonePlan } from '@/components/startups/MilestonePlan';
import { ConfirmButton, SubmitButton } from '@/components/ui/FormButtons';
import { accessibleStartupWhere, canDeleteTaskRecord, canEditTaskRecord, canManageStartupMembers, hasPermission, hasStartupPermission, isProgramRole, requireSession, startupMemberRole } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

const dateInput = (date: Date | null | undefined) => date ? date.toISOString().slice(0, 10) : '';
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase();
const inputClass = 'h-10 w-full rounded-input border bg-white px-3 text-sm outline-none focus:border-prise-primary';

export default async function StartupDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireSession();
  const { id } = await params;
  if (session.user.role === Role.INVESTOR) return <InvestorStartupDetail startupId={id} investorId={session.user.id} />;
  const startup = await prisma.startup.findFirst({
    where: { id, ...accessibleStartupWhere(session.user) },
    include: {
      milestones: { orderBy: [{ phase: 'asc' }, { dueDate: 'asc' }], include: {
        template: { select: { phaseName: true } },
        stakeholderStatuses: { include: { updatedBy: { select: { name: true } } } },
        deliverables: { where: { status: { not: DeliverableStatus.ARCHIVED } }, orderBy: { createdAt: 'desc' }, include: { uploader: { select: { name: true } }, reviewer: { select: { name: true } } } },
        reviews: { orderBy: { createdAt: 'desc' }, take: 1, include: { reviewer: { select: { name: true } } } },
      } },
      tasks: { orderBy: [{ status: 'asc' }, { dueDate: 'asc' }], include: { assignee: { select: { name: true } }, createdBy: { select: { name: true } } } },
      memberships: { where: { isActive: true, person: { isActive: true } }, orderBy: [{ role: 'asc' }, { createdAt: 'asc' }], include: { person: { select: { id: true, name: true, email: true, isActive: true } } } },
      supportRequests: { orderBy: { createdAt: 'desc' } },
      paymentInstallments: { orderBy: { dueDate: 'desc' } },
    },
  });
  if (!startup) notFound();
  const people = await prisma.person.findMany({ where: isProgramRole(session.user.role) ? { isActive: true } : { isActive: true, OR: [{ id: session.user.id }, { founderOfStartupId: id }, { startupMemberships: { some: { startupId: id, isActive: true } } }, { assignments: { some: { startupId: id } } }] }, orderBy: { name: 'asc' }, select: { id: true, name: true, role: true } });
  const memberRole = await startupMemberRole(id, session.user.id) ?? (session.user.founderOfStartupId === id ? StartupMemberRole.OWNER : null);
  const canEdit = hasStartupPermission(session.user.role, 'startup:update', memberRole);
  const canReviewOnboarding = hasPermission(session.user.role, 'onboarding:review');
  const canAssign = isProgramRole(session.user.role) || session.user.role === Role.MENTOR || session.user.role === Role.FOUNDER;
  const canTask = hasStartupPermission(session.user.role, 'task:manage', memberRole);
  const canReviewMilestone = hasPermission(session.user.role, 'milestone:review');
  const canUploadEvidence = (session.user.role === Role.FOUNDER || session.user.role === Role.PROGRAM_LEAD) && hasStartupPermission(session.user.role, 'deliverable:upload', memberRole);
  const canPayment = hasStartupPermission(session.user.role, 'payment:manage', memberRole);
  const canSupportCreate = hasStartupPermission(session.user.role, 'support:create', memberRole);
  const canSupportManage = hasPermission(session.user.role, 'support:manage');
  const canManageMembers = canManageStartupMembers(session.user.role, memberRole);
  const paid = Number(startup.totalFeePaid ?? 0);
  const agreed = Number(startup.agreedFee ?? 0);
  const feeProgress = agreed > 0 ? Math.min(100, Math.round((paid / agreed) * 100)) : 0;
  const completedMilestones = startup.milestones.filter((item) => item.status === MilestoneStatus.APPROVED).length;
  const milestoneProgress = startup.milestones.length ? Math.round((completedMilestones / startup.milestones.length) * 100) : 0;
  const currentMilestone = startup.milestones.find((item) => item.status !== MilestoneStatus.APPROVED) ?? startup.milestones.at(-1);
  const currentPhase = currentMilestone?.phase ?? 1;
  const currentPhaseName = currentMilestone?.template?.phaseName ?? `Phase ${currentPhase}`;
  const priorityMilestones = startup.milestones.filter((item) => item.status !== MilestoneStatus.APPROVED).sort((a, b) => Number(b.priority === Priority.HIGH) - Number(a.priority === Priority.HIGH) || a.phase - b.phase).slice(0, 3);
  const overdueTasks = startup.tasks.filter((item) => item.status !== TaskStatus.DONE && item.dueDate && item.dueDate < new Date()).length;
  const revisionItems = startup.milestones.filter((item) => item.status === MilestoneStatus.NEEDS_REVISION || item.stakeholderStatuses.some((lane) => lane.state === 'NEEDS_REVISION' || lane.state === 'BLOCKED')).length;
  const overduePayments = startup.paymentInstallments.filter((item) => item.status === PaymentStatus.OVERDUE).length;
  const riskReasons = [
    overdueTasks ? `${overdueTasks} overdue task${overdueTasks === 1 ? '' : 's'}` : null,
    revisionItems ? `${revisionItems} milestone${revisionItems === 1 ? '' : 's'} need correction` : null,
    overduePayments ? `${overduePayments} overdue payment${overduePayments === 1 ? '' : 's'}` : null,
    startup.status === StartupStatus.NEEDS_ATTENTION ? startup.healthStatus || 'Program team marked this startup for attention' : null,
  ].filter((item): item is string => Boolean(item));
  const healthLabel = startup.status === StartupStatus.NEEDS_ATTENTION || riskReasons.length >= 2 ? 'At risk' : riskReasons.length ? 'Attention' : 'Healthy';
  const healthTone = healthLabel === 'Healthy' ? 'bg-success-bg text-success' : healthLabel === 'Attention' ? 'bg-warning-bg text-warning' : 'bg-danger-bg text-danger';

  return <div className="mx-auto w-full max-w-[1450px] p-4 sm:p-6 lg:p-8">
    <div className="mb-5 flex items-center justify-between"><Link href="/startups" className="text-sm font-semibold text-prise-text-secondary hover:text-prise-primary">← Back to startups</Link>{canEdit ? <Link href={`/startups/${id}/edit`} className="inline-flex items-center gap-2 rounded-button border bg-white px-3 py-2 text-sm font-semibold"><Pencil size={15} /> Edit profile</Link> : null}</div>
    <div className="rounded-card bg-prise-sidebar p-6 text-white shadow-card sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-sm text-white/55">PRISE 3.0 · Startup 360</div><h1 className="mt-2 max-w-4xl text-2xl font-bold tracking-[-.025em] sm:text-3xl">{startup.name}</h1><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm text-white/68"><span>{startup.founderName}</span><span>{startup.sector}</span>{startup.operationLocation ? <span className="inline-flex items-center gap-1.5"><MapPin size={14} />{startup.operationLocation}, {startup.state}</span> : null}</div></div><div className="rounded-button bg-white/9 px-4 py-3"><div className="text-xs uppercase tracking-[.08em] text-white/48">Operating status</div><div className="mt-1 text-sm font-semibold">{label(startup.status)}</div></div></div></div>

    <nav className="sticky top-0 z-10 mt-4 flex gap-1 overflow-x-auto rounded-xl border border-prise-border bg-white/95 p-1.5 shadow-sm backdrop-blur" aria-label="Startup workspace shortcuts"><a href="#overview" className="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold text-prise-text-secondary hover:bg-prise-page">Overview</a><a href="#milestones" className="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold text-prise-text-secondary hover:bg-prise-page">Milestones</a><Link href="/work" className="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold text-prise-text-secondary hover:bg-prise-page">Tasks</Link><Link href="/resources" className="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold text-prise-text-secondary hover:bg-prise-page">Resources</Link><Link href="/calendar" className="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold text-prise-text-secondary hover:bg-prise-page">Calendar</Link><Link href="/tickets" className="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold text-prise-text-secondary hover:bg-prise-page">Tickets</Link></nav>

    <div id="overview" className="mt-5 grid scroll-mt-20 gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <div className="space-y-5">
        {(startup.status === StartupStatus.APPLICATION_PENDING || startup.status === StartupStatus.REJECTED) && canReviewOnboarding ? <Section title="Application decision" subtitle="Approve a complete application or return it with one clear reason."><form action={reviewStartupApplicationAction} className="grid gap-3 sm:grid-cols-[180px_1fr_auto]"><input type="hidden" name="startupId" value={id} /><select name="decision" className={inputClass}><option value="APPROVE">Approve application</option><option value="REJECT">Return for changes</option></select><input name="remarks" placeholder="Decision note (required when returned)" className={inputClass} /><SubmitButton>Save decision</SubmitButton></form></Section> : null}
        <Section title="Startup overview" subtitle="The essential profile, health and next priorities in one decision-ready view.">
          <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Health" value={healthLabel} tone={healthTone} /><MetricCard label="Milestones done" value={`${completedMilestones}/${startup.milestones.length}`} /><MetricCard label="Current phase" value={`${currentPhase}`} detail={currentPhaseName} /><MetricCard label="Overall progress" value={`${milestoneProgress}%`} /></div>
          <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-prise-page p-4"><div className="text-xs font-semibold uppercase tracking-[.1em] text-prise-text-secondary">Profile details</div><dl className="mt-3 grid grid-cols-[100px_1fr] gap-x-3 gap-y-2 text-sm"><dt className="text-prise-text-muted">Founder</dt><dd className="font-medium">{startup.founderName}</dd><dt className="text-prise-text-muted">Sector</dt><dd className="font-medium">{startup.sector || 'Not added'}</dd><dt className="text-prise-text-muted">Location</dt><dd className="font-medium">{startup.operationLocation || startup.state || 'Not added'}</dd><dt className="text-prise-text-muted">Address</dt><dd className="font-medium">{startup.fullAddress || 'Not added'}</dd><dt className="text-prise-text-muted">Structure</dt><dd className="font-medium">{startup.legalStructure || 'Not added'}</dd></dl></div><div className="rounded-xl bg-prise-page p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.1em] text-prise-text-secondary">{riskReasons.length ? <AlertTriangle size={14} className={healthLabel === 'At risk' ? 'text-danger' : 'text-warning'} /> : <CheckCircle2 size={14} className="text-success" />}Health reasons</div><div className="mt-3 space-y-2">{riskReasons.length ? riskReasons.map((reason) => <div key={reason} className="text-sm text-prise-text-secondary">• {reason}</div>) : <div className="text-sm text-success">No overdue or revision signals detected.</div>}</div></div></div>
          <div className="mt-4 rounded-xl border p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.1em] text-prise-text-secondary"><Target size={14} className="text-prise-primary" />Priority milestones</div><div className="mt-3 grid gap-2 sm:grid-cols-3">{priorityMilestones.map((item) => <a key={item.id} href="#milestones" className="rounded-lg bg-prise-page p-3"><div className="text-[10px] font-semibold uppercase text-prise-primary">Phase {item.phase} · {label(item.priority)}</div><div className="mt-1 text-sm font-semibold leading-5">{item.title}</div></a>)}{priorityMilestones.length === 0 ? <div className="text-sm text-success sm:col-span-3">All selected milestones are complete.</div> : null}</div></div>
        </Section>

        <MilestonePlan startupId={id} milestones={startup.milestones} role={session.user.role} currentUserId={session.user.id} canAssign={canAssign} canReview={canReviewMilestone} canUpload={canUploadEvidence} />

        <Section title="Tasks" subtitle="Execution commitments tied to the startup or a milestone.">
          {canTask ? <details className="mb-4 rounded-input border border-dashed p-4"><summary className="cursor-pointer text-sm font-semibold text-prise-primary">+ Add task</summary><form action={createTaskAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="startupId" value={id} /><input name="title" required placeholder="Task outcome" className={inputClass} /><select name="milestoneId" className={inputClass}><option value="">No milestone</option>{startup.milestones.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="assigneeId" className={inputClass}><option value="">Assign to me</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name} · {label(person.role)}</option>)}</select><select name="priority" defaultValue={Priority.NORMAL} className={inputClass}>{Object.values(Priority).map((value) => <option key={value}>{value}</option>)}</select><input name="dueDate" type="date" className={inputClass} /><textarea name="description" placeholder="Definition of done" rows={3} className="rounded-input border p-3 sm:col-span-2" /><div className="sm:col-span-2"><SubmitButton>Create task</SubmitButton></div></form></details> : null}
          <div className="space-y-3">{startup.tasks.map((task) => <details key={task.id} className="rounded-input border p-4"><summary className="cursor-pointer list-none"><div className="flex justify-between gap-3"><div><div className="text-sm font-semibold">{task.title}</div><div className="mt-1 text-xs text-prise-text-secondary">{task.assignee ? `Assigned to ${task.assignee.name}` : 'Unassigned'}{task.createdBy ? ` · Created by ${task.createdBy.name}` : ''}</div></div><Badge value={task.status} /></div></summary>{canTask && canEditTaskRecord(session.user, task) ? <div className="mt-4 border-t pt-4"><form action={updateTaskAction} className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="taskId" value={task.id} /><input name="title" defaultValue={task.title} required className={inputClass} /><select name="status" defaultValue={task.status} className={inputClass}>{Object.values(TaskStatus).map((value) => <option key={value}>{value}</option>)}</select><select name="priority" defaultValue={task.priority} className={inputClass}>{Object.values(Priority).map((value) => <option key={value}>{value}</option>)}</select><input name="dueDate" type="date" defaultValue={dateInput(task.dueDate)} className={inputClass} /><select name="assigneeId" defaultValue={task.assigneeId ?? ''} className={inputClass}><option value="">Unassigned</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name} · {label(person.role)}</option>)}</select><input name="blockedReason" defaultValue={task.blockedReason ?? ''} placeholder="Blocked reason" className={inputClass} /><textarea name="description" defaultValue={task.description ?? ''} rows={2} className="rounded-input border p-3 sm:col-span-2" /><div><SubmitButton>Update task</SubmitButton></div></form>{canDeleteTaskRecord(session.user, task) ? <form action={deleteTaskAction} className="mt-2"><input type="hidden" name="taskId" value={task.id} /><ConfirmButton message="Delete this task? The deletion will remain visible in the audit history.">Delete task</ConfirmButton></form> : null}</div> : null}</details>)}{startup.tasks.length === 0 ? <Empty text="No tasks yet." /> : null}</div>
        </Section>
      </div>

      <div className="space-y-5">
        <Section title="Startup team" subtitle="Members share this startup workspace with role-based editing rights.">
          <div className="space-y-3">{startup.memberships.map((membership) => <div key={membership.id} className="rounded-input border p-3"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-semibold">{membership.person.name}</div><div className="text-xs text-prise-text-secondary">{membership.person.email}</div></div><Badge value={membership.isActive ? membership.role : 'INACTIVE'} /></div>{canManageMembers && membership.role !== StartupMemberRole.OWNER ? <form action={updateStartupMemberAction} className="mt-3 grid gap-2 border-t pt-3 sm:grid-cols-[1fr_auto_auto]"><input type="hidden" name="membershipId" value={membership.id} /><select name="memberRole" defaultValue={membership.role} className={inputClass}>{[StartupMemberRole.ADMIN, StartupMemberRole.MEMBER, StartupMemberRole.FINANCE, StartupMemberRole.VIEWER].map((value) => <option key={value}>{value}</option>)}</select><label className="flex items-center gap-2 px-2 text-xs font-semibold"><input type="checkbox" name="isActive" defaultChecked={membership.isActive} /> Active</label><SubmitButton className="!py-2">Update</SubmitButton></form> : null}</div>)}</div>
          {canManageMembers ? <details className="mt-4 rounded-input border border-dashed p-4"><summary className="cursor-pointer text-sm font-semibold text-prise-primary">+ Add startup member</summary><form action={createStartupMemberAction} className="mt-4 grid gap-2 sm:grid-cols-2"><input type="hidden" name="startupId" value={id} /><input name="name" required placeholder="Member name" className={inputClass} /><input name="email" type="email" required placeholder="Email" className={inputClass} /><select name="memberRole" defaultValue={StartupMemberRole.MEMBER} className={inputClass}>{[StartupMemberRole.ADMIN, StartupMemberRole.MEMBER, StartupMemberRole.FINANCE, StartupMemberRole.VIEWER].map((value) => <option key={value}>{value}</option>)}</select><input name="password" type="password" required minLength={6} placeholder="Temporary password (6+ characters)" className={inputClass} /><div className="sm:col-span-2"><SubmitButton>Add member</SubmitButton></div></form></details> : null}
        </Section>
        <Section title="Fee position" icon={<IndianRupee size={17} className="text-prise-primary" />}><div className="flex items-end justify-between gap-4"><div><div className="text-3xl font-bold">₹{paid.toLocaleString('en-IN')}</div><div className="text-xs text-prise-text-secondary">received</div></div><div className="text-sm text-prise-text-secondary">of {agreed ? `₹${agreed.toLocaleString('en-IN')}` : 'not set'}</div></div><div className="mt-4 h-2 overflow-hidden rounded-pill bg-[#ececf3]"><div className="h-full rounded-pill bg-success" style={{ width: `${feeProgress}%` }} /></div>{canPayment ? <PaymentCreate startupId={id} /> : null}<div className="mt-4 space-y-3">{startup.paymentInstallments.map((payment) => <PaymentRow key={payment.id} payment={payment} canEdit={canPayment} />)}</div></Section>

        <Section title="Support requests" subtitle="Ask for a mentor, expert, intern or program intervention.">{canSupportCreate ? <details className="mb-4 rounded-input border border-dashed p-4"><summary className="cursor-pointer text-sm font-semibold text-prise-primary">+ Request support</summary><form action={createSupportAction} className="mt-4 space-y-3"><input type="hidden" name="startupId" value={id} /><input name="title" required placeholder="What support is needed?" className={inputClass} /><textarea name="description" rows={3} placeholder="Context and desired outcome" className="w-full rounded-input border p-3 text-sm" /><div className="grid grid-cols-2 gap-2"><select name="priority" defaultValue={Priority.NORMAL} className={inputClass}>{Object.values(Priority).map((value) => <option key={value}>{value}</option>)}</select><input name="dueDate" type="date" className={inputClass} /></div><SubmitButton>Create request</SubmitButton></form></details> : null}<div className="space-y-3">{startup.supportRequests.map((request) => <details key={request.id} className="rounded-input border p-4"><summary className="cursor-pointer list-none"><div className="flex justify-between gap-3"><div className="text-sm font-semibold">{request.title}</div><Badge value={request.status} /></div></summary>{canSupportManage ? <div className="mt-4 border-t pt-4"><form action={updateSupportAction} className="space-y-2"><input type="hidden" name="requestId" value={request.id} /><select name="status" defaultValue={request.status} className={inputClass}>{Object.values(SupportRequestStatus).map((value) => <option key={value}>{value}</option>)}</select><select name="assignedToId" defaultValue={request.assignedToId ?? ''} className={inputClass}><option value="">Unassigned</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name} · {label(person.role)}</option>)}</select><input name="dueDate" type="date" defaultValue={dateInput(request.dueDate)} className={inputClass} /><textarea name="outcome" defaultValue={request.outcome ?? ''} rows={2} placeholder="Outcome / resolution" className="w-full rounded-input border p-3 text-sm" /><SubmitButton>Update request</SubmitButton></form><form action={deleteSupportAction} className="mt-2"><input type="hidden" name="requestId" value={request.id} /><ConfirmButton message="Delete this support request?">Delete request</ConfirmButton></form></div> : <p className="mt-3 text-sm text-prise-text-secondary">{request.description}</p>}</details>)}{startup.supportRequests.length === 0 ? <Empty text="No support requests." /> : null}</div></Section>

        <Section title="Audit snapshot" icon={<ShieldCheck size={17} className="text-prise-primary" />}><p className="text-sm leading-6 text-prise-text-secondary">Every mutation on this page records the actor, role, timestamp and change context.</p>{hasPermission(session.user.role, 'audit:view') ? <Link href={`/audit?startupId=${id}`} className="mt-4 inline-flex text-sm font-semibold text-prise-primary">View startup history →</Link> : null}</Section>
      </div>
    </div>
  </div>;
}

function Section({ title, subtitle, children, action, icon }: { title: string; subtitle?: string; children: React.ReactNode; action?: React.ReactNode; icon?: React.ReactNode }) { return <section className="rounded-card border bg-white p-5 shadow-card sm:p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="flex items-center gap-2">{icon}<h2 className="text-base font-semibold">{title}</h2></div>{subtitle ? <p className="mt-1 text-sm text-prise-text-secondary">{subtitle}</p> : null}</div>{action}</div>{children}</section>; }
function MetricCard({ label: metricLabel, value, detail, tone = 'bg-prise-page text-prise-text' }: { label: string; value: string; detail?: string; tone?: string }) { return <div className={`rounded-xl p-3 ${tone}`}><div className="text-[10px] font-semibold uppercase tracking-[.1em] opacity-65">{metricLabel}</div><div className="mt-1 text-xl font-bold">{value}</div>{detail ? <div className="mt-0.5 truncate text-[10px] opacity-70">{detail}</div> : null}</div>; }
function Badge({ value }: { value: string }) { return <span className="shrink-0 rounded-pill bg-prise-page px-2.5 py-1 text-[11px] font-semibold text-prise-text-secondary">{label(value)}</span>; }
function Empty({ text }: { text: string }) { return <div className="rounded-input bg-prise-page p-4 text-sm text-prise-text-secondary">{text}</div>; }

async function InvestorStartupDetail({ startupId, investorId }: { startupId: string; investorId: string }) {
  const share = await prisma.investorStartupShare.findUnique({
    where: { startupId_investorId: { startupId, investorId } },
    include: { startup: { select: { name: true, sector: true, state: true, operationLocation: true, healthStatus: true, milestones: { where: { status: MilestoneStatus.APPROVED }, orderBy: [{ phase: 'asc' }, { approvedAt: 'desc' }], select: { id: true, phase: true, title: true, deliverable: true, approvedAt: true, deliverables: { where: { status: DeliverableStatus.APPROVED }, select: { id: true, name: true } } } } } } },
  });
  if (!share) notFound();
  const startup = share.startup;
  return <div className="mx-auto w-full max-w-5xl p-4 sm:p-6 lg:p-8"><Link href="/portfolio" className="text-sm font-semibold text-prise-text-secondary">← Back to portfolio</Link><section className="mt-5 rounded-card bg-prise-sidebar p-6 text-white shadow-card sm:p-8"><div className="text-xs font-semibold uppercase tracking-[.12em] text-white/55">Approved investor view</div><h1 className="mt-2 text-3xl font-bold">{startup.name}</h1><p className="mt-2 text-sm text-white/68">{startup.sector || 'Sector not specified'} · {startup.operationLocation || startup.state || 'Location not specified'}</p><p className="mt-5 max-w-3xl text-sm leading-6 text-white/75">{startup.healthStatus || 'No program-approved summary has been published yet.'}</p></section><section className="mt-5 rounded-card border bg-white p-5 shadow-card sm:p-6"><h2 className="text-lg font-bold">Approved progress</h2><p className="mt-1 text-sm text-prise-text-secondary">Internal onboarding, payments, support requests and working files are intentionally excluded.</p><div className="mt-5 space-y-3">{startup.milestones.map((milestone) => <div key={milestone.id} className="rounded-xl border p-4"><div className="text-xs font-semibold text-prise-primary">Phase {milestone.phase}</div><div className="mt-1 font-semibold">{milestone.title}</div><p className="mt-1 text-sm text-prise-text-secondary">{milestone.deliverable || 'Approved milestone outcome'}</p>{share.canViewDocuments && milestone.deliverables.length ? <div className="mt-3 flex flex-wrap gap-2">{milestone.deliverables.map((file) => <a key={file.id} href={`/api/documents/${file.id}`} className="rounded-lg border px-3 py-2 text-xs font-semibold text-prise-primary">{file.name}</a>)}</div> : null}</div>)}{startup.milestones.length === 0 ? <div className="rounded-xl border border-dashed p-8 text-center text-sm text-prise-text-secondary">No approved milestones have been shared yet.</div> : null}</div></section></div>;
}

function PaymentCreate({ startupId }: { startupId: string }) { return <details className="mt-5 rounded-input border border-dashed p-4"><summary className="cursor-pointer text-sm font-semibold text-prise-primary"><Plus size={15} className="mr-1 inline" />Add installment</summary><form action={createPaymentAction} className="mt-4 grid gap-2 sm:grid-cols-2"><input type="hidden" name="startupId" value={startupId} /><input name="amount" type="number" min="1" step="0.01" required placeholder="Amount" className={inputClass} /><input name="dueDate" type="date" required className={inputClass} /><select name="status" defaultValue={PaymentStatus.PENDING} className={inputClass}>{Object.values(PaymentStatus).map((value) => <option key={value}>{value}</option>)}</select><input name="paidAt" type="date" className={inputClass} /><input name="reference" placeholder="Reference" className={inputClass} /><input name="remarks" placeholder="Remarks" className={inputClass} /><div className="sm:col-span-2"><SubmitButton>Add installment</SubmitButton></div></form></details>; }

function PaymentRow({ payment, canEdit }: { payment: { id: string; amount: { toString(): string }; dueDate: Date; paidAt: Date | null; status: PaymentStatus; reference: string | null; remarks: string | null }; canEdit: boolean }) { return <details className="rounded-input border p-3"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-semibold">₹{Number(payment.amount).toLocaleString('en-IN')}</div><div className="text-xs text-prise-text-secondary">{payment.dueDate.toLocaleDateString('en-IN')}</div></div><Badge value={payment.status} /></div></summary>{canEdit ? <div className="mt-3 border-t pt-3"><form action={updatePaymentAction} className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="paymentId" value={payment.id} /><input name="amount" type="number" min="1" step="0.01" defaultValue={payment.amount.toString()} className={inputClass} /><input name="dueDate" type="date" defaultValue={dateInput(payment.dueDate)} className={inputClass} /><select name="status" defaultValue={payment.status} className={inputClass}>{Object.values(PaymentStatus).map((value) => <option key={value}>{value}</option>)}</select><input name="paidAt" type="date" defaultValue={dateInput(payment.paidAt)} className={inputClass} /><input name="reference" defaultValue={payment.reference ?? ''} placeholder="Reference" className={inputClass} /><input name="remarks" defaultValue={payment.remarks ?? ''} placeholder="Remarks" className={inputClass} /><SubmitButton>Update payment</SubmitButton></form><form action={deletePaymentAction} className="mt-2"><input type="hidden" name="paymentId" value={payment.id} /><ConfirmButton message="Delete this payment installment?">Delete installment</ConfirmButton></form></div> : null}</details>; }
