import Image from 'next/image';
import Link from 'next/link';
import { CalendarClock, ExternalLink, MapPin } from 'lucide-react';
import { AssignmentRole, MatchPreferenceSource, MilestoneStatus, Role, StartupStatus } from '@prisma/client';
import { finalizeMentorMatchAction } from '@/app/actions/matching';
import { PreferencePicker } from '@/components/directory/PreferencePicker';
import { SubmitButton } from '@/components/ui/FormButtons';
import { isProgramRole, requireSession, resolveFounderStartupId } from '@/lib/auth';
import { roleLabel } from '@/lib/labels';
import { prisma } from '@/lib/prisma';
import { accessibleStartupProfileIds } from '@/lib/startup-profile-access';

export const dynamic = 'force-dynamic';
type DirectoryView = 'mentors' | 'incubatees' | 'program';

export default async function DirectoryPage({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  const session = await requireSession();
  const requested = (await searchParams).view;
  const view: DirectoryView = requested === 'incubatees' || requested === 'program' ? requested : 'mentors';
  const founderStartupId = session.user.role === Role.FOUNDER ? await resolveFounderStartupId(session.user) : null;
  const [mentors, startups, programPeople, preferences, mentorAssignments] = await Promise.all([
    prisma.person.findMany({ where: { role: Role.MENTOR, isActive: true }, orderBy: { name: 'asc' }, select: { id: true, name: true, organization: true, designation: true, professionalBio: true, professionalDomain: true, mentorLocation: true, mentoringFrequency: true, linkedinUrl: true, expertiseAreas: true, preferredSectors: true, languages: true, yearsExperience: true, profilePhotoKey: true } }),
    prisma.startup.findMany({ where: { status: { in: [StartupStatus.ACTIVE, StartupStatus.NEEDS_ATTENTION] } }, orderBy: [{ sNo: 'asc' }, { name: 'asc' }], select: { id: true, name: true, founderName: true, sector: true, operationLocation: true, state: true, legalStructure: true, healthStatus: true, logoStorageKey: true, profilePdfStorageKey: true, founder: { select: { id: true, profilePhotoKey: true } }, milestones: { select: { phase: true, status: true, title: true, priority: true }, orderBy: [{ phase: 'asc' }, { priority: 'desc' }] } } }),
    prisma.person.findMany({ where: { role: { in: [Role.PROGRAM_LEAD, Role.PROGRAM_TEAM, Role.INTERN, Role.EXPERT] }, isActive: true }, orderBy: [{ role: 'asc' }, { name: 'asc' }], select: { id: true, name: true, email: true, role: true, organization: true, designation: true, professionalBio: true, profilePhotoKey: true } }),
    prisma.mentorMatchPreference.findMany({ include: { mentor: { select: { id: true, name: true } }, startup: { select: { id: true, name: true } } }, orderBy: [{ source: 'asc' }, { rank: 'asc' }, { createdAt: 'asc' }] }),
    isProgramRole(session.user.role) ? prisma.startupAssignment.findMany({ where: { role: AssignmentRole.MENTOR }, select: { startupId: true, personId: true } }) : Promise.resolve([]),
  ]);
  const initialMentorIds = founderStartupId ? preferences.filter((item) => item.source === MatchPreferenceSource.INCUBATEE && item.startupId === founderStartupId).sort((a, b) => a.rank - b.rank).map((item) => item.mentorId) : [];
  const initialStartupIds = preferences.filter((item) => item.source === MatchPreferenceSource.MENTOR && item.mentorId === session.user.id).sort((a, b) => a.rank - b.rank).map((item) => item.startupId);
  const profileStartupIds = await accessibleStartupProfileIds(session.user, startups.filter(({ profilePdfStorageKey }) => Boolean(profilePdfStorageKey)).map(({ id }) => id));

  return <div className="mx-auto w-full max-w-[1350px] p-4 sm:p-6 lg:p-8">
    <div><div className="text-xs font-semibold uppercase tracking-[.12em] text-prise-primary">People</div><h1 className="mt-1 text-2xl font-bold tracking-tight">Directory</h1><p className="mt-1.5 text-sm text-prise-text-secondary">Discover the cohort, submit preferences and keep final access controlled by the program team.</p></div>
    <nav className="mt-6 flex gap-1 overflow-x-auto rounded-xl border bg-white p-1" aria-label="Directory views"><Tab href="/directory?view=mentors" active={view === 'mentors'} label="Mentors" count={mentors.length} /><Tab href="/directory?view=incubatees" active={view === 'incubatees'} label="Incubatees" count={startups.length} /><Tab href="/directory?view=program" active={view === 'program'} label="Program team" count={programPeople.length} /></nav>

    {view === 'mentors' ? <div className="mt-6 space-y-6">{session.user.role === Role.FOUNDER ? <section><SectionTitle title="Choose mentors" description="Compare domain, location, experience and mentoring frequency, then arrange your preference order." /><PreferencePicker noun="mentor" initialIds={initialMentorIds} candidates={mentors.map((mentor) => ({ id: mentor.id, title: mentor.name, subtitle: [mentor.designation, mentor.organization].filter(Boolean).join(' · ') || 'Mentor', meta: mentor.professionalDomain || undefined, description: mentor.professionalBio ?? undefined, imageUrl: mentor.profilePhotoKey ? `/api/profile-photo/${mentor.id}` : undefined, chips: mentor.expertiseAreas, stats: [mentor.mentorLocation || 'Location not added', mentor.mentoringFrequency || 'Flexible', mentor.yearsExperience === null ? 'Experience not added' : `${mentor.yearsExperience} years`], profileHref: `/mentors/${mentor.id}` }))} /></section> : <ProfileGrid>{mentors.map((mentor) => <MentorCard key={mentor.id} mentor={mentor} />)}</ProfileGrid>}{isProgramRole(session.user.role) ? <MatchingReport preferences={preferences} assignments={mentorAssignments} /> : null}</div> : null}
    {view === 'incubatees' ? <div className="mt-6">{session.user.role === Role.MENTOR ? <section><SectionTitle title="Choose incubatees" description="Compare startup context and progress, then arrange your preference order." /><PreferencePicker noun="incubatee" initialIds={initialStartupIds} candidates={startups.map((startup) => { const approved = startup.milestones.filter((item) => item.status === MilestoneStatus.APPROVED).length; const currentPhase = startup.milestones.find((item) => item.status !== MilestoneStatus.APPROVED)?.phase ?? startup.milestones.at(-1)?.phase; const priorities = startup.milestones.filter((item) => item.status !== MilestoneStatus.APPROVED).slice(0, 2).map((item) => item.title); return { id: startup.id, title: startup.name, subtitle: [startup.sector, startup.operationLocation || startup.state].filter(Boolean).join(' · ') || 'Incubatee', meta: currentPhase ? `Currently in Phase ${currentPhase}` : 'Milestone plan pending', description: startup.healthStatus ?? `Led by ${startup.founderName}`, imageUrl: startup.logoStorageKey ? `/api/startup-logo/${startup.id}` : undefined, chips: priorities, stats: [`${approved}/${startup.milestones.length} milestones complete`, startup.founderName], profileHref: profileStartupIds.has(startup.id) ? `/startups/${startup.id}/profile` : undefined }; })} /></section> : <ProfileGrid>{startups.map((startup) => <IncubateeCard key={startup.id} startup={startup} canOpen={isProgramRole(session.user.role)} canViewProfile={profileStartupIds.has(startup.id)} />)}</ProfileGrid>}</div> : null}
    {view === 'program' ? <ProfileGrid className="mt-6">{programPeople.map((person) => <article key={person.id} className="rounded-card border bg-white p-5 shadow-card"><PersonAvatar id={person.id} name={person.name} hasPhoto={Boolean(person.profilePhotoKey)} /><h2 className="mt-4 font-semibold">{person.name}</h2><p className="mt-1 text-xs font-semibold text-prise-primary">{roleLabel(person.role)}</p><p className="mt-2 text-sm text-prise-text-secondary">{[person.designation, person.organization].filter(Boolean).join(' · ') || 'PrISE program delivery'}</p>{person.professionalBio ? <p className="mt-3 line-clamp-3 text-xs leading-5 text-prise-text-secondary">{person.professionalBio}</p> : null}<a href={`mailto:${person.email}`} className="mt-4 block truncate text-xs font-semibold text-prise-primary">{person.email}</a></article>)}</ProfileGrid> : null}
  </div>;
}

function Tab({ href, active, label, count }: { href: string; active: boolean; label: string; count: number }) { return <Link href={href} className={`whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold ${active ? 'bg-prise-primary text-white' : 'text-prise-text-secondary hover:bg-prise-page'}`}>{label} <span className={active ? 'text-white/70' : 'text-prise-text-muted'}>{count}</span></Link>; }
function SectionTitle({ title, description }: { title: string; description: string }) { return <div className="mb-4"><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-prise-text-secondary">{description}</p></div>; }
function ProfileGrid({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`grid gap-4 sm:grid-cols-2 xl:grid-cols-3 ${className}`}>{children}</div>; }
function Avatar({ name }: { name: string }) { return <div className="flex h-12 w-12 items-center justify-center rounded-full bg-accent-purple-bg text-sm font-bold text-accent-purple">{name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()}</div>; }
function PersonAvatar({ id, name, hasPhoto }: { id: string; name: string; hasPhoto: boolean }) { return hasPhoto ? <div className="relative h-12 w-12 overflow-hidden rounded-full"><Image src={`/api/profile-photo/${id}`} alt={`${name} profile`} fill sizes="48px" className="object-cover" unoptimized /></div> : <Avatar name={name} />; }

function MentorCard({ mentor }: { mentor: { id: string; name: string; organization: string | null; designation: string | null; professionalBio: string | null; professionalDomain: string | null; mentorLocation: string | null; mentoringFrequency: string | null; linkedinUrl: string | null; expertiseAreas: string[]; languages: string[]; yearsExperience: number | null; profilePhotoKey: string | null } }) {
  return <article className="flex min-h-64 flex-col rounded-card border bg-white p-5 shadow-card"><div className="flex items-center gap-3"><PersonAvatar id={mentor.id} name={mentor.name} hasPhoto={Boolean(mentor.profilePhotoKey)} /><div className="min-w-0"><h2 className="truncate font-semibold">{mentor.name}</h2><p className="truncate text-xs text-prise-text-secondary">{[mentor.designation, mentor.organization].filter(Boolean).join(' · ') || 'Mentor'}</p></div></div>{mentor.professionalDomain ? <p className="mt-4 text-sm font-semibold leading-5 text-prise-text">{mentor.professionalDomain}</p> : null}<div className="mt-3 grid gap-2 text-xs text-prise-text-secondary"><span className="flex items-center gap-2"><MapPin size={14} className="shrink-0 text-prise-primary" />{mentor.mentorLocation || 'Location not added'}</span><span className="flex items-center gap-2"><CalendarClock size={14} className="shrink-0 text-prise-primary" />{mentor.mentoringFrequency || 'Flexible / As required'}</span></div><div className="mt-4 flex flex-wrap gap-1.5">{mentor.expertiseAreas.slice(0, 4).map((item) => <span key={item} className="rounded-pill bg-prise-page px-2.5 py-1 text-[11px] font-semibold">{item}</span>)}</div><div className="mt-auto flex items-center justify-between gap-3 border-t pt-4 text-xs"><span className="text-prise-text-secondary">{mentor.yearsExperience === null ? 'Experience not added' : `${mentor.yearsExperience} years experience`}</span><span className="flex items-center gap-3">{mentor.linkedinUrl ? <a href={mentor.linkedinUrl} target="_blank" rel="noreferrer" aria-label={`${mentor.name} on LinkedIn`} className="text-prise-primary"><ExternalLink size={15} /></a> : null}<Link href={`/mentors/${mentor.id}`} className="font-semibold text-prise-primary">View profile →</Link></span></div></article>;
}

function IncubateeCard({ startup, canOpen, canViewProfile }: { startup: { id: string; name: string; founderName: string; sector: string | null; operationLocation: string | null; state: string | null; legalStructure: string | null; healthStatus: string | null; logoStorageKey: string | null; founder: { id: string; profilePhotoKey: string | null } | null; milestones: { phase: number; status: MilestoneStatus; title: string }[] }; canOpen: boolean; canViewProfile: boolean }) {
  const approved = startup.milestones.filter((item) => item.status === MilestoneStatus.APPROVED).length;
  const currentPhase = startup.milestones.find((item) => item.status !== MilestoneStatus.APPROVED)?.phase ?? startup.milestones.at(-1)?.phase;
  return <article className="flex min-h-64 flex-col rounded-card border bg-white p-5 shadow-card"><div className="flex items-center gap-3">{startup.logoStorageKey ? <div className="relative h-14 w-14 shrink-0 overflow-hidden rounded-xl border bg-white"><Image src={`/api/startup-logo/${startup.id}`} alt={`${startup.name} logo`} fill sizes="56px" className="object-contain p-1.5" unoptimized /></div> : <Avatar name={startup.name} />}<div className="min-w-0"><h2 className="line-clamp-2 font-semibold leading-5">{startup.name}</h2><p className="mt-1 truncate text-xs text-prise-text-secondary">{startup.founderName} · Incubatee</p></div></div><div className="mt-4 flex flex-wrap gap-1.5"><span className="rounded-pill bg-prise-page px-2.5 py-1 text-[11px] font-semibold">{startup.sector || 'Sector pending'}</span><span className="rounded-pill bg-prise-page px-2.5 py-1 text-[11px] font-semibold">{startup.operationLocation || startup.state || 'Location pending'}</span>{startup.legalStructure ? <span className="rounded-pill bg-prise-page px-2.5 py-1 text-[11px] font-semibold">{startup.legalStructure}</span> : null}</div><p className="mt-4 text-xs font-semibold text-prise-primary">{currentPhase ? `Phase ${currentPhase} · ${approved}/${startup.milestones.length} complete` : 'Milestone plan pending'}</p>{startup.healthStatus ? <p className="mt-2 line-clamp-2 text-xs leading-5 text-prise-text-secondary">{startup.healthStatus}</p> : null}<div className="mt-auto flex items-center gap-4 border-t pt-4">{canViewProfile ? <Link href={`/startups/${startup.id}/profile`} className="text-xs font-semibold text-prise-primary">More info →</Link> : null}{canOpen ? <Link href={`/startups/${startup.id}`} className="text-xs font-semibold text-prise-primary">Open Startup 360 →</Link> : null}</div></article>;
}

function MatchingReport({ preferences, assignments }: { preferences: Array<{ id: string; source: MatchPreferenceSource; rank: number; createdAt: Date; mentorId: string; startupId: string; mentor: { id: string; name: string }; startup: { id: string; name: string } }>; assignments: Array<{ startupId: string; personId: string }> }) {
  const assigned = new Set(assignments.map((item) => `${item.startupId}:${item.personId}`));
  const pairs = new Map<string, { mentorChoice?: (typeof preferences)[number]; incubateeChoice?: (typeof preferences)[number] }>();
  for (const item of preferences) { const key = `${item.startupId}:${item.mentorId}`; const pair = pairs.get(key) ?? {}; if (item.source === MatchPreferenceSource.MENTOR) pair.mentorChoice = item; else pair.incubateeChoice = item; pairs.set(key, pair); }
  const rows = [...pairs.values()].sort((a, b) => Number(Boolean(b.mentorChoice && b.incubateeChoice)) - Number(Boolean(a.mentorChoice && a.incubateeChoice)) || (a.mentorChoice?.rank ?? a.incubateeChoice?.rank ?? 99) - (b.mentorChoice?.rank ?? b.incubateeChoice?.rank ?? 99) || (a.mentorChoice?.createdAt ?? a.incubateeChoice!.createdAt).getTime() - (b.mentorChoice?.createdAt ?? b.incubateeChoice!.createdAt).getTime());
  return <section className="rounded-card border bg-white shadow-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Matching report</h2><p className="mt-1 text-sm text-prise-text-secondary">Mutual preferences appear first. Program Lead or Program Team finalizes workspace access.</p></div><div className="divide-y">{rows.map(({ mentorChoice, incubateeChoice }) => { const choice = mentorChoice ?? incubateeChoice!; const finalized = assigned.has(`${choice.startupId}:${choice.mentorId}`); const mutual = Boolean(mentorChoice && incubateeChoice); return <div key={`${choice.startupId}:${choice.mentorId}`} className="grid gap-3 px-5 py-4 text-sm md:grid-cols-[1fr_1fr_auto_auto] md:items-center"><div><div className="font-semibold">{choice.startup.name}</div><div className="text-xs text-prise-text-secondary">Incubatee rank {incubateeChoice?.rank ?? '—'}</div></div><div><div className="font-semibold">{choice.mentor.name}</div><div className="text-xs text-prise-text-secondary">Mentor rank {mentorChoice?.rank ?? '—'}</div></div><span className={`w-fit rounded-pill px-2.5 py-1 text-[11px] font-semibold ${mutual ? 'bg-success-bg text-success' : 'bg-warning-bg text-warning'}`}>{mutual ? 'Mutual match' : 'One-sided'}</span>{finalized ? <span className="text-xs font-semibold text-success">Finalized</span> : <form action={finalizeMentorMatchAction}><input type="hidden" name="startupId" value={choice.startupId} /><input type="hidden" name="mentorId" value={choice.mentorId} /><SubmitButton className="!py-2">Finalize</SubmitButton></form>}</div>; })}{rows.length === 0 ? <div className="p-6 text-sm text-prise-text-secondary">No preferences submitted yet.</div> : null}</div></section>;
}
